const data = [
  {
    id: 1,
    foodName: 'Buttermilk Pancakes',
    info: "I'm baby woke mlkshk wolf bitters live-edge blue bottle, hammock freegan copper mug whatever cold-pressed",
    price: 15,
    image: 'food-1.jpeg',
    type: 'breakfast',
  },
  {
    id: 2,
    foodName: 'Country Delight',
    info: 'Shabby chic keffiyeh neutra snackwave pork belly shoreditch. Prism austin mlkshk truffaut,',
    price: 15,
    image: 'food-2.jpeg',
    type: 'breakfast',
  },
  {
    id: 3,
    foodName: 'Buttermilk Pancakes',
    info: 'carry jianbing normcore freegan. Viral single-origin coffee live-edge, pork belly cloud bread iceland put a bird',
    price: 15,
    image: 'food-3.jpeg',
    type: 'breakfast',
  },
  {
    id: 4,
    foodName: 'Diner Double',
    info: 'vaporware iPhone mumblecore selvage raw denim slow-carb leggings gochujang helvetica man braid jianbing. Marfa thundercats',
    price: 15,
    image: 'food-4.jpeg',
    type: 'lunch',
  },
  {
    id: 5,
    foodName: 'Egg Attack',
    info: "franzen vegan pabst bicycle rights kickstarter pinterest meditation farm-to-table 90's pop-up",
    price: 15,
    image: 'food-5.jpeg',
    type: 'lunch',
  },
  {
    id: 6,
    foodName: 'American Classic',
    info: 'on it tumblr kickstarter thundercats migas everyday carry squid palo santo leggings. Food truck truffaut',
    price: 15,
    image: 'food-6.jpeg',
    type: 'lunch',
  },
  {
    id: 7,
    foodName: 'Godzilla Milkshake',
    info: 'ombucha chillwave fanny pack 3 wolf moon street art photo booth before they sold out organic viral.',
    price: 15,
    image: 'food-7.jpeg',
    type: 'shakes',
  },
  {
    id: 8,
    foodName: 'Oreo Dream',
    info: 'Portland chicharrones ethical edison bulb, palo santo craft beer chia heirloom iPhone everyday',
    price: 15,
    image: 'food-8.jpeg',
    type: 'shakes',
  },
  {
    id: 9,
    foodName: 'Quarantine Buddy',
    info: 'skateboard fam synth authentic semiotics. Live-edge lyft af, edison bulb yuccie crucifix microdosing.',
    price: 15,
    image: 'food-9.jpeg',
    type: 'shakes',
  },
];

export default data;
